export const SET_IS_BETA_AUTH = 'app/GET_WORDS'
export const FIRST_PAGE_LOAD = 'app/FIRST_PAGE_LOAD'
export const SHOW_LOADER = 'app/SHOW_LOADER'
export const HIDE_LOADER = 'app/HIDE_LOADER'
export const SHOW_ALERT = 'app/SHOW_ALERT'
export const HIDE_ALERT = 'app/HIDE_ALERT'